---
- name: getting all azure VM facts
  hosts: localhost

  tasks:
  - name: running the facts module
    azure_rm_virtualmachineimage_info: 
      location: westeurope
      publisher: RedHat
      # offer: byos
      offer: rhel-byos
      # sku: rhel-lvm8
      sku: rhel-lvm75
      # sku: rhel-lvm74
      # version: 8.0.2019050711
    register: vm_results

  - name: return data
    debug: 
      var: vm_results
