---
- name: Create Azure Public IP
  hosts: localhost
  connection: local
  gather_facts: no

  tasks:
    - name: Create Public IP address
      azure_rm_publicipaddress:
        resource_group: 1-b3c32a4e-playground-sandbox
        name: arupPublicIP
        allocation_method: Static
        location: westus
