- name: create Azure VM
  hosts: localhost
  vars_files: 
#    - /home/ansible/secvar/azure_cred.yml
   - /home/ansible/secvar/ssh_keys.yml

  tasks: 
  - name: setup real clients
    azure_rm_virtualmachine:
      resource_group: "{{ resourcegroup_name }}"
      name: "{{ vm_hostname }}-rhel7.5-{{ item }}"
      vm_size: Standard_A2
      admin_username: ansible
      ssh_password_enabled: false
      ssh_public_keys: 
      - path: /home/ansible/.ssh/authorized_keys
        key_data: "{{ automata_sshkey }}"
      image:
        publisher: RedHat
        offer: rhel-byos
        sku: rhel-lvm75
        version: 7.5.20190205
      public_ip_allocation_method: Disabled
      plan:
        product: rhel-byos
        publisher: redhat
        name: rhel-lvm75
    loop: "{{ range(0, 1)|list }}" 
   
  - name: setup real clients
    azure_rm_virtualmachine:
      resource_group: "{{ resourcegroup_name }}"
      name: "{{ vm_hostname }}-rhel8.0-{{ item }}"
      vm_size: Standard_A2
      admin_username: ansible
      ssh_password_enabled: false
      ssh_public_keys: 
      - path: /home/ansible/.ssh/authorized_keys
        key_data: "{{ automata_sshkey }}"
      image:
        publisher: RedHat
        offer: rhel-byos
        sku: rhel-lvm8
        version: 8.0.20190620
      public_ip_allocation_method: Disabled
      plan:
        product: rhel-byos
        publisher: redhat
        name: rhel-lvm8
    loop: "{{ range(0, 1)|list }}" 
   
  - name: setup real clients
    azure_rm_virtualmachine:
      resource_group: "{{ resourcegroup_name }}"
      name: "{{ vm_hostname }}-rhel7.4.0-{{ item }}"
      vm_size: Standard_A2
      admin_username: ansible
      ssh_password_enabled: false
      ssh_public_keys: 
      - path: /home/ansible/.ssh/authorized_keys
        key_data: "{{ automata_sshkey }}"
      image:
        publisher: RedHat
        offer: rhel-byos
        sku: rhel-lvm74
        version: 7.4.20180511
      public_ip_allocation_method: Disabled
      plan:
        product: rhel-byos
        publisher: redhat
        name: rhel-lvm74
    loop: "{{ range(0, 1)|list }}" 
  
